# Generated by Django 6.0.4 on 2026-04-11 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reg_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_a', to='library.document')),
                ('reg_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_b', to='library.document')),
            ],
            options={
                'verbose_name_plural': 'comparison analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClausePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_a_article', models.CharField(max_length=50)),
                ('reg_b_article', models.CharField(blank=True, max_length=50)),
                ('match_type', models.CharField(choices=[('equivalent', 'Equivalent'), ('partial', 'Partial'), ('similar', 'Similar'), ('none', 'No match')], default='none', max_length=20)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('ai_analysis', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_pairs', to='comparison.comparisonanalysis')),
            ],
        ),
    ]
