# Generated by Django 6.0.4 on 2026-04-19 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
        ('library', '0003_add_metadata_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_a', models.CharField(max_length=200)),
                ('citation_b', models.CharField(blank=True, max_length=200)),
                ('preview_a', models.TextField(blank=True)),
                ('preview_b', models.TextField(blank=True)),
                ('clause_text_a', models.TextField(blank=True)),
                ('clause_text_b', models.TextField(blank=True)),
                ('relationship', models.CharField(choices=[('equivalent', 'Equivalent'), ('stricter_in_a', 'Stricter in A'), ('stricter_in_b', 'Stricter in B'), ('additional_in_a', 'Additional in A'), ('additional_in_b', 'Additional in B'), ('conflicting', 'Conflicting')], default='equivalent', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('rationale', models.TextField(blank=True)),
                ('key_difference', models.TextField(blank=True)),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('principle_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='system', max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('from_lifecycle', models.CharField(blank=True, max_length=20)),
                ('to_lifecycle', models.CharField(blank=True, max_length=20)),
                ('diff', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='comparison.comparisonresult')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_key', models.CharField(max_length=10)),
                ('topics', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('partially_failed', 'Partially failed')], default='pending', max_length=20)),
                ('completed_pairs', models.PositiveIntegerField(default=0)),
                ('total_pairs', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reg_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs_as_a', to='library.document')),
                ('reg_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs_as_b', to='library.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='comparison.comparisonrun'),
        ),
    ]
