# Generated by Django 6.0.4 on 2026-04-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0002_comparisonresult_auditevent_comparisonrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonresult',
            name='citation_verified',
            field=models.BooleanField(default=True),
        ),
    ]
