# Generated by Django 6.0.4 on 2026-04-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0003_add_citation_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='lifecycle',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='relationship',
            field=models.CharField(choices=[('equivalent', 'Equivalent'), ('stricter_in_a', 'Stricter in A'), ('stricter_in_b', 'Stricter in B'), ('additional_in_a', 'Additional in A'), ('additional_in_b', 'Additional in B'), ('conflicting', 'Conflicting')], db_index=True, default='equivalent', max_length=20),
        ),
        migrations.AlterField(
            model_name='comparisonrun',
            name='pair_key',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='comparisonrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('partially_failed', 'Partially failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
