# Generated by Django 5.2.13 on 2026-05-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0004_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonresult',
            name='chunk_id_a',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='chunk_id_b',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='evidence_a',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='evidence_b',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='hallucination_risk',
            field=models.FloatField(default=0.0),
        ),
    ]
