# Generated by Django 5.2.13 on 2026-05-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0005_comparisonresult_chunk_id_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonrun',
            name='report_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
