# Generated by Django 5.2.13 on 2026-05-14 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0006_comparisonrun_report_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonrun',
            name='analyst_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_comparison_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
