# Generated by Django 5.2.15 on 2026-08-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0007_comparisonrun_analyst_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonresult',
            name='compliance_impact',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='practical_conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='shared_controls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='terminology_note',
            field=models.TextField(blank=True),
        ),
    ]
