# Generated by Django 5.2.15 on 2026-08-13 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0008_comparisonresult_compliance_impact_and_more'),
        ('library', '0017_topicsuggestion_requirementtopic_suggestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonrun',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_comparison_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='assessment_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='currency_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='currency_state',
            field=models.CharField(choices=[('current', 'Current'), ('outdated', 'Outdated — a source has changed'), ('unknown', 'Cannot verify currency')], db_index=True, default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='lifecycle',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded by a newer approved version')], db_index=True, default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='model_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='outdated_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='source_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_run', to='comparison.comparisonrun'),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='taxonomy_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='comparisonrun',
            name='version_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comparisonrun',
            name='pair_key',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='comparisonrun',
            index=models.Index(fields=['lifecycle', '-approved_at'], name='comparison__lifecyc_2bd62e_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonrun',
            index=models.Index(fields=['assessment_key', '-version_no'], name='comparison__assessm_4b9d14_idx'),
        ),
    ]
