# Generated by Django 5.2.15 on 2026-08-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0010_backfill_run_assessments'),
        ('library', '0017_topicsuggestion_requirementtopic_suggestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonrun',
            name='reg_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs_as_a', to='library.document'),
        ),
        migrations.AlterField(
            model_name='comparisonrun',
            name='reg_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs_as_b', to='library.document'),
        ),
    ]
