# Generated by Django 6.0.4 on 2026-04-11 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('review', 'In Review'), ('approved', 'Approved')], default='running', max_length=20)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('obligation_count', models.PositiveIntegerField(default=0)),
                ('gap_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_analyses', to='library.document')),
                ('regulations', models.ManyToManyField(blank=True, related_name='mappings_against', to='library.document')),
            ],
            options={
                'verbose_name_plural': 'mapping analyses',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='ObligationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_ref', models.CharField(max_length=50)),
                ('obligation_title', models.CharField(max_length=255)),
                ('coverage', models.CharField(choices=[('covered', 'Covered'), ('partial', 'Partial'), ('review', 'Requires Review'), ('none', 'Not Covered')], default='none', max_length=20)),
                ('evidence_text', models.TextField(blank=True)),
                ('evidence_source', models.CharField(blank=True, max_length=255)),
                ('confidence_pct', models.PositiveSmallIntegerField(default=0)),
                ('human_override', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_mappings', to='mapping.mappinganalysis')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.document')),
            ],
        ),
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('remediation_text', models.TextField(blank=True)),
                ('remediation_source', models.CharField(choices=[('ai', 'AI Suggested'), ('human', 'Human Written'), ('edited', 'AI + Edited')], default='ai', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='mapping.mappinganalysis')),
                ('obligation_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='mapping.obligationmapping')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
