# Generated by Django 6.0.4 on 2026-04-20 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_mappinganalysis_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='gap',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='current_obligation_label',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='include_asymmetric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='progress_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='progress_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='scope_article_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='scope_mode',
            field=models.CharField(choices=[('full', 'All topics'), ('topics', 'Selected topics'), ('specific', 'Specific articles')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='scope_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='highlighted_phrases',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='lifecycle',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='obligation_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='reviewer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='severity',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='topics',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gap',
            name='obligation_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='mapping.obligationmapping', unique=True),
        ),
        migrations.AlterField(
            model_name='gap',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='gap',
            name='remediation_source',
            field=models.CharField(choices=[('ai_drafted', 'AI Drafted'), ('ai_draft_edited', 'AI Draft Edited'), ('human_written', 'Human Written')], default='ai_drafted', max_length=20),
        ),
        migrations.AlterField(
            model_name='mappinganalysis',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('review', 'In Review'), ('approved', 'Approved')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='obligationmapping',
            name='article_ref',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='obligationmapping',
            name='evidence_source',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='obligationmapping',
            name='obligation_title',
            field=models.CharField(max_length=300),
        ),
    ]
