# Generated by Django 6.0.4 on 2026-04-21 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_v2_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='obligation_mapping',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gap', to='mapping.obligationmapping'),
        ),
    ]
