# Generated by Django 6.0.4 on 2026-04-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_gap_obligation_mapping_onetoone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gap',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='mappinganalysis',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('review', 'In Review'), ('approved', 'Approved')], db_index=True, default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='obligationmapping',
            name='coverage',
            field=models.CharField(choices=[('covered', 'Covered'), ('partial', 'Partial'), ('review', 'Requires Review'), ('none', 'Not Covered')], db_index=True, default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='obligationmapping',
            name='lifecycle',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified')], db_index=True, default='draft', max_length=20),
        ),
    ]
