# Generated by Django 5.2.13 on 2026-05-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligationmapping',
            name='citation_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='hallucination_risk',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='policy_chunk_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='regulation_chunk_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='obligationmapping',
            name='regulation_evidence',
            field=models.TextField(blank=True),
        ),
    ]
