# Generated by Django 5.2.13 on 2026-05-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_obligationmapping_citation_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gap',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaps_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gap',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gap',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
