# Generated by Django 5.2.13 on 2026-05-14 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0008_add_auto_scope_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mappinganalysis',
            name='analyst_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_mapping_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mappinganalysis',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
