# Generated by Django 5.2.15 on 2026-08-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0009_mappinganalysis_analyst_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappinganalysis',
            name='skipped_topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
