# Generated by Django 5.2.15 on 2026-08-11 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0014_requirement'),
        ('mapping', '0010_mappinganalysis_skipped_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligationmapping',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='library.requirement'),
        ),
    ]
