# Generated by Django 5.2.15 on 2026-08-06 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('modify', 'Modify')], db_index=True, max_length=12)),
                ('source_app', models.CharField(db_index=True, default='comparison', max_length=40)),
                ('source_id', models.PositiveIntegerField(db_index=True)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=120)),
                ('query', models.TextField(blank=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('taxonomy_version', models.CharField(blank=True, max_length=40)),
                ('model_version', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoldExemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=120)),
                ('query', models.TextField(blank=True)),
                ('reg_a', models.CharField(blank=True, max_length=160)),
                ('reg_b', models.CharField(blank=True, max_length=160)),
                ('payload', models.JSONField(default=dict)),
                ('source_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('taxonomy_version', models.CharField(blank=True, max_length=40)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
