# Generated by Django 6.0.4 on 2026-04-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20),
        ),
    ]
