# Generated by Django 5.2.13 on 2026-05-12 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_ingestionjob_created_by'),
        ('library', '0006_document_applicable_sector_document_concept_tags_csv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantinedChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('node_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('rule_id', models.CharField(db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium')], db_index=True, default='high', max_length=10)),
                ('tier', models.CharField(choices=[('A', 'Tier A — regex catalog'), ('B', 'Tier B — LLM judge')], default='A', max_length=1)),
                ('rule_description', models.CharField(blank=True, max_length=255)),
                ('matched_snippet', models.TextField(blank=True)),
                ('judge_reason', models.TextField(blank=True)),
                ('all_detections', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved (released to index)'), ('rejected', 'Rejected (permanently quarantined)')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('chunk_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_decisions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantined_chunks', to='library.document')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantined_chunks', to='ingestion.ingestionjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ingestion_q_status_74f526_idx'), models.Index(fields=['severity', '-created_at'], name='ingestion_q_severit_3f7a33_idx')],
            },
        ),
    ]
